// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp_ControleDeGastos.Database;

namespace WebApp_ControleDeGastos.Migrations
{
    [DbContext(typeof(SistemaFinanceiroDBContext))]
    partial class SistemaFinanceiroDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApp_ControleDeGastos.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .UseIdentityColumn();

                    b.Property<decimal>("Balance")
                        .HasColumnType("DECIMAL(15,2)");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<decimal>("InvoiceAmount")
                        .HasColumnType("DECIMAL(15,2)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("Limite")
                        .HasColumnType("DECIMAL(15,2)");

                    b.Property<int>("NumberCard")
                        .HasColumnType("INT");

                    b.Property<long>("Nome")
                        .HasColumnType("BIGINT");

                    b.Property<byte>("type")
                        .HasColumnType("TINYINT");

                    b.HasKey("CardId");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("WebApp_ControleDeGastos.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("WebApp_ControleDeGastos.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DateTime");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(60)");

                    b.Property<int>("NumberCard")
                        .HasColumnType("INT");

                    b.Property<int>("NumberInstallments")
                        .HasColumnType("INT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(15,2)");

                    b.Property<byte>("type")
                        .HasColumnType("TINYINT");

                    b.HasKey("ExpenseId");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("WebApp_ControleDeGastos.Models.Revenue", b =>
                {
                    b.Property<int>("RevenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(15,2)");

                    b.HasKey("RevenueId");

                    b.ToTable("Revenue");
                });

            modelBuilder.Entity("WebApp_ControleDeGastos.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .UseIdentityColumn();

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
